import type { ResearchResponse } from "../schemas/aiResearch.schema.js";
import { prisma } from "../lib/prisma.js";

function slugify(value: string): string {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

function truncateSeoDescription(value: string, maxLength = 320): string {
  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, maxLength - 3).trim()}...`;
}

function normalizeHtmlContent(value: string): string {
  let content = value
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .trim();

  // Remove Markdown code fences if Gemini accidentally wraps the HTML.
  content = content
    .replace(/^```html\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();

  // Convert any H1 generated by Gemini to H2.
  // The application stores the article title separately,
  // so article content should never contain an H1.
  content = content
    .replace(/<h1(\s[^>]*)?>/gi, "<h2$1>")
    .replace(/<\/h1>/gi, "</h2>");

  // Remove accidental whitespace between HTML tags.
  content = content
    .replace(/>\s+</g, ">\n<")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return content;
}

async function generateUniqueSlug(title: string): Promise<string> {
  const baseSlug = slugify(title);
  let slug = baseSlug;
  let counter = 1;

  while (
    await prisma.post.findUnique({
      where: { slug },
      select: { id: true },
    })
  ) {
    slug = `${baseSlug}-${counter}`;
    counter++;
  }

  return slug;
}

export async function saveResearchResults(
  research: ResearchResponse,
) {
  const saved = [];

  for (const discovery of research.discoveries) {
    const publishedAt = new Date(discovery.publishedAt);

    console.log("\nDiscovery:", discovery.title);
    console.log("Published:", discovery.publishedAt);
    console.log("Source:", discovery.url);

    // Ignore discoveries with invalid publication dates.
    if (Number.isNaN(publishedAt.getTime())) {
      console.log("IGNORED: Invalid publication date");
      continue;
    }

    // Prevent the same source from being inserted multiple times.
    const existingPost = await prisma.post.findFirst({
      where: {
        content: {
          contains: discovery.url,
        },
      },
      select: {
        id: true,
        title: true,
        slug: true,
      },
    });

    if (existingPost) {
      console.log(
        `IGNORED: Duplicate source. Existing post #${existingPost.id}`,
      );
      continue;
    }

    const slug = await generateUniqueSlug(discovery.title);

    const content = normalizeHtmlContent(`
${discovery.content}

<h2>Source</h2>

<p>
  <a href="${discovery.url}" target="_blank" rel="noopener noreferrer">
    ${discovery.source}
  </a>
</p>
`);

    const post = await prisma.post.create({
      data: {
        title: discovery.title,
        slug,
        excerpt: discovery.summary,
        content,
        seoTitle: discovery.title,
        seoDescription: truncateSeoDescription(discovery.summary),
        published: false,
        publishedAt: new Date(),
      },
    });

    console.log(`SAVED: Post #${post.id}`);

    saved.push(post);
  }

  return {
    saved,
  };
}